from functools import partial

from ppotune.arbiters.pairwise_arbiter import (
    RemotePairwiseArbiter,
    SequentialRemotePairwiseArbiter
)


GSM8K_PAIRWISE_SYSTEM_PROMPT = '''You are evaluating the performance of different language models on a math problem-solving task. Each model is given a grade school math word problem from the GSM8K dataset and tasked with producing a correct and well-reasoned final answer. Your job is to compare the outputs and select the model that solves the problem best from a human perspective.

## Problem

{{
    "question": """{prompt}"""
}}

## Model completions

The following are unordered completions with solutions generated by different models. Each output is associated with a unique model identifier.

{{
    {{
        "model_identifier": "0",
        "output": """{response0}"""
    }},
    {{
        "model_identifier": "1",
        "output": """{response1}"""
    }}
}}

## Task

Select the model that produced the best solution to the math problem. Consider both correctness and clarity of reasoning. Reply with the identifier of the best model. Our evaluation will only consider the first character of your answer, so ensure your response contains only one of the identifiers and nothing else (no quotation marks, no spaces, no new lines, ...).
'''


gsm8k_arbiter = partial(
    RemotePairwiseArbiter,
    system_prompt = GSM8K_PAIRWISE_SYSTEM_PROMPT
)
gsm8k_arbiter.__doc__ = """
Builder for arbiter assesing models on reasoning task.
"""

sequential_gsm8k_arbiter = partial(
    SequentialRemotePairwiseArbiter,
    system_prompt = GSM8K_PAIRWISE_SYSTEM_PROMPT
)
sequential_gsm8k_arbiter.__doc__="""
Builder for arbiter assesing models on resoning task with calling internal LLM
API sequentially (check `SequentialRemotePairwiseArbiter` doc for more info).
"""
