from functools import partial

from ppotune.arbiters.pairwise_arbiter import (
    RemotePairwiseArbiter,
    SequentialRemotePairwiseArbiter
)


TLDR_PAIRWISE_SYSTEM_PROMPT = '''You are evaluating the performance of different language models on a summarization task. Each model is given a Reddit post from the trl-lib/tldr dataset and tasked with generating a concise and accurate summary. Your job is to compare the outputs and select the model that produces the best summary from a human perspective.

## Post

{{
    "post": """{prompt}"""",
}}

## Model completions

The following are unordered completions with summaries generated by different models. Each output is associated with a unique model identifier.

{{
    {{
        "model_identifier": "0",
        "output": """{response0}"""
    }},
    {{
        "model_identifier": "1",
        "output": """{response1}"""
    }}
}}

## Task

Select the model that generated the best summary. Reply with the identifier of the best model. Our evaluation will only consider the first character of your answer, so ensure your response contains only one of the identifiers and nothing else (no quotation marks, no spaces, no new lines, ...).
'''


tldr_arbiter = partial(
    RemotePairwiseArbiter,
    system_prompt = TLDR_PAIRWISE_SYSTEM_PROMPT
)
tldr_arbiter.__doc__ = """
Builder for arbiters assesing models on summarization task.
"""

sequential_tldr_arbiter = partial(
    SequentialRemotePairwiseArbiter,
    system_prompt = TLDR_PAIRWISE_SYSTEM_PROMPT
)
sequential_tldr_arbiter.__doc__ = """
Builder for arbiters assesing models on summarization task with calling 
internal LLM API sequentially (check `SequentialRemotePairwiseArbiter` doc 
for more info).
"""
